services:
  mitplan:
    container_name: mitplan
    build:
      context: .
      dockerfile: Dockerfile.develop
    depends_on:
      - mitplan-postgres
      - mitplan-redis
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - REDIS_URL=${REDIS_URL}
      - FRONTEND_URL=${REACT_APP_BACKEND_URL}
    secrets:
      - db_password
      - jwt_secret
    networks:
      - mitplan-network
    volumes:
      - ~/mitplan/mitplan-frontend:/app/frontend
      - ~/mitplan/mitplan-backend:/app/backend
    ports:
      - 9229:9229

  mitplan-postgres:
    container_name: mitplan-postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ${HOST_POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - mitplan-network

  mitplan-redis:
    container_name: mitplan-redis
    image: redis:6
    networks:
      - mitplan-network

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

networks:
  mitplan-network:
    driver: bridge